# Generated by Django 3.1.1 on 2023-05-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_auto_20230423_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('label_type', models.CharField(choices=[('Semantic', 'Semantic'), ('Non-Semantic', 'Non-Semantic')], default='Non-Semantic', max_length=300)),
                ('qid', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('platform', models.CharField(default='', max_length=300)),
                ('link', models.CharField(default='', max_length=300)),
                ('post_link', models.URLField(default='', max_length=300)),
                ('image', models.FileField(blank=True, default='../static/default_post_image.png', upload_to='posts')),
                ('is_private', models.BooleanField(blank=True, default=False, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_by', models.ManyToManyField(blank=True, null=True, related_name='vookmarked_posts', to='user.User')),
                ('label', models.ManyToManyField(blank=True, null=True, to='feed.Label')),
                ('liked_by', models.ManyToManyField(blank=True, null=True, related_name='liked_posts', to='user.User')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_posts', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(blank=True, default=False, null=True)),
                ('member', models.ManyToManyField(blank=True, null=True, related_name='member_of_spaces', to='user.User')),
                ('moderator', models.ManyToManyField(blank=True, null=True, related_name='moderator_of_spaces', to='user.User')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_spaces', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='http://www.w3.org/ns/anno.jsonld', max_length=255)),
                ('type', models.CharField(default='Annotation', max_length=255)),
                ('target', models.JSONField(blank=True, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceModeratorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_moderator_request_user', to='user.user')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_moderator_request_space', to='feed.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceMemberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_member_request_user', to='user.user')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_member_request_space', to='feed.space')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_report', to='feed.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_posts', to='feed.space'),
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('body_description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation_created_by', to='user.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation', to='feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_review', to='feed.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='user.user')),
            ],
        ),
    ]
