# Generated by Django 3.1.1 on 2023-05-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextAnnotation',
            new_name='Annotation',
        ),
        migrations.DeleteModel(
            name='ImageAnnotation',
        ),
    ]
