# Generated by Django 3.1.1 on 2022-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("feed", "0002_post_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="liked_posts", to="user.User"
            ),
        ),
    ]
