# Generated by Django 3.1.1 on 2023-03-21 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20230320_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
