# Generated by Django 3.1.1 on 2023-03-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friendrequest_friends'),
        ('feed', '0003_post_post_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarked_posts', to='user.User'),
        ),
    ]
