# Generated by Django 3.1.1 on 2022-12-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_resetpassword'),
        ('feed', '0003_post_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='vookmarked_posts', to='user.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_link',
            field=models.URLField(default='', max_length=300),
        ),
    ]
