# Generated by Django 3.1.1 on 2023-03-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friendrequest_friends'),
        ('feed', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='moderator',
            field=models.ManyToManyField(blank=True, null=True, related_name='moderator_of_spaces', to='user.User'),
        ),
    ]
