# Generated by Django 3.1.1 on 2023-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
