# Generated by Django 3.1.1 on 2023-05-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230423_2106'),
        ('feed', '0006_space_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='label_type',
            field=models.CharField(choices=[('Semantic', 'Semantic'), ('Non-Semantic', 'Non-Semantic')], default='Non-Semantic', max_length=300),
        ),
        migrations.AddField(
            model_name='label',
            name='qid',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='space',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_of_spaces', to='user.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='../static/default_post_image.png', upload_to='posts'),
        ),
        migrations.CreateModel(
            name='textAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('body_description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('selector_type', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_annotation_created_by', to='user.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_annotation', to='feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceModeratorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_moderator_request_user', to='user.user')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_moderator_request_space', to='feed.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceMemberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_member_request_user', to='user.user')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_member_request_space', to='feed.space')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_report', to='feed.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('body_description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation_created_by', to='user.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation', to='feed.post')),
            ],
        ),
    ]
