# Generated by Django 3.1.1 on 2023-04-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230404_1357'),
        ('feed', '0006_space_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='../static/default_post_image.png', null=True, upload_to='posts'),
        ),
        migrations.CreateModel(
            name='textAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('body_description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('selector_type', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='user.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_annotation', to='feed.post')),
            ],
        ),
    ]
