# Generated by Django 3.1.1 on 2023-04-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_space_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='../static/default_post_image.png', null=True, upload_to='posts'),
        ),
    ]
