# Generated by Django 3.1.1 on 2023-04-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friendrequest_friends'),
        ('feed', '0006_space_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='textAnnotation',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('type', models.TextField()),
                ('body_description', models.TextField(unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('selector_type', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='user.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_annotation', to='feed.post')),
            ],
        ),
    ]
