# Generated by Django 3.1.1 on 2023-04-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230404_1357'),
        ('feed', '0006_space_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_of_spaces', to='user.User'),
        ),
        migrations.CreateModel(
            name='SpaceJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_request_user', to='user.user')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_request_space', to='feed.space')),
            ],
        ),
    ]
