# Generated by Django 3.1.1 on 2023-05-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230423_2106'),
        ('feed', '0006_space_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='http://www.w3.org/ns/anno.jsonld', max_length=255)),
                ('annotation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(default='Annotation', max_length=255)),
                ('target', models.JSONField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('creator', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_of_spaces', to='user.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='../static/default_post_image.png', upload_to='posts'),
        ),
        migrations.CreateModel(
            name='SpaceModeratorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_moderator_request_user', to='user.user')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_moderator_request_space', to='feed.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceMemberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_member_request_user', to='user.user')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_member_request_space', to='feed.space')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('body_description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation_created_by', to='user.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation', to='feed.post')),
            ],
        ),
    ]
