# Generated by Django 3.1.1 on 2023-05-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20230513_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textannotation',
            name='annotation_id',
        ),
        migrations.RemoveField(
            model_name='textannotation',
            name='creator',
        ),
        migrations.AlterField(
            model_name='textannotation',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
