# Generated by Django 3.1.1 on 2023-04-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20230419_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='qid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
