# Generated by Django 3.1.1 on 2023-04-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230423_2106'),
        ('feed', '0007_auto_20230419_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_of_spaces', to='user.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='../static/default_post_image.png', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='textannotation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_annotation_created_by', to='user.user'),
        ),
        migrations.AlterField(
            model_name='textannotation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_annotation', to='feed.post'),
        ),
        migrations.CreateModel(
            name='SpaceModeratorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_moderator_request_user', to='user.user')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_moderator_request_space', to='feed.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceMemberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_member_request_user', to='user.user')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_member_request_space', to='feed.space')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('body_description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation_created_by', to='user.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation', to='feed.post')),
            ],
        ),
    ]
