# Generated by Django 3.1.1 on 2023-04-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20230409_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
