# Generated by Django 3.1.1 on 2023-05-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230423_2106'),
        ('feed', '0007_auto_20230501_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_body', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feed.textannotation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_annotation_reply_created_by', to='user.user')),
            ],
        ),
    ]
