# Generated by Django 3.1.1 on 2023-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20230419_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='../static/default_post_image.png', upload_to='posts'),
        ),
    ]
