# Generated by Django 3.1.1 on 2023-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_textannotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textannotation',
            name='body_description',
            field=models.TextField(),
        ),
    ]
