# Generated by Django 3.1.1 on 2023-05-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20230423_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
