# Generated by Django 3.1.1 on 2023-04-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20230410_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textannotation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
