# Generated by Django 3.1.1 on 2023-05-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_annotationcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationcomment',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='annotationcomment',
            old_name='reply_body',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='textannotation',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='textannotation',
            name='body',
        ),
    ]
