# Generated by Django 3.1.1 on 2023-05-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20230423_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='label_type',
            field=models.CharField(choices=[('Semantic', 'Semantic'), ('Non-Semantic', 'Non-Semantic')], default='Non-Semantic', max_length=300),
        ),
    ]
