# Generated by Django 3.1.1 on 2023-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20230513_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='qid',
            field=models.CharField(default='', max_length=300),
        ),
    ]
