# Generated by Django 3.1.1 on 2023-05-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_label_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
