# Generated by Django 3.1.1 on 2023-05-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
