# Generated by Django 3.1.1 on 2023-05-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20230511_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
    ]
