# Generated by Django 3.1.1 on 2023-05-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_semantictag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemanticTag',
        ),
    ]
