version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate --noinput && 
             python manage.py migrate --database=annotation_db --noinput &&         
             python manage.py runserver 0.0.0.0:8000"
             
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
      - annotation_db
    volumes:
      - ./app:/app
      - media_volume:/app/media
      - static_volume:/app/static
    env_file:
      - ./.env
  db:
    image: postgres:12-alpine
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
  annotation_db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "5432:5432"

volumes:
  my_dbdata:
  media_volume:
  static_volume:
