# Generated by Django 3.1.1 on 2023-04-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230423_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold')]),
        ),
    ]
